routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Home
Route::get('/', 'ContentController@home');

// ADMIN
Route::get('/admin', 'Auth\LoginController@getAdmin');

// Route::get('/cambiar-contraseña', function () {
//     return view('emails.contact');
// });

//Login
Route::post('/iniciar-sesion', 'Auth\LoginController@postLogin');

// Logout
Route::get('/cerrar-sesion','Auth\LoginController@getLogout');

//Change pass
Route::get('/cambiar-contrasena', 'Auth\ResetPasswordController@index');
Route::post('/cambiar-contrasena/{id}', 'Auth\ResetPasswordController@update');

//Galery
Route::resource('galeria', 'GaleryController');
Route::get('/admin/galeria', 'GaleryController@index');
Route::delete('/admin/galeria/delete/{id}', ['as' => 'galeria.delete', 'uses' => 'GaleryController@destroy']);
Route::get('/admin/galeria/delete-item/{id}', ['as' => 'galeria.delete.item', 'uses' => 'GaleryController@destroyItem']);


Route::resource('noticias', 'NoticesController');
Route::get('/admin/noticias', 'NoticesController@index');
Route::delete('/admin/noticias/delete/{id}', ['as' => 'noticias.delete', 'uses' => 'NoticesController@destroy']);
Route::get('/admin/noticias/delete-item/{id}', ['as' => 'noticias.delete.item', 'uses' => 'NoticesController@destroyItem']);


Route::post('/send-email', 'EmailController@send');

// PUBLIC
Route::get('/nosotros', function () {
    return view('partials.about.more');
});

Route::get('/noticias', 'ContentController@moreNotices');
Route::get('/galeria', 'ContentController@moreGalery');

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Media;
use App\MediaNotice;
use Auth;

class Notice extends Model
{
	protected $table = 'notices';
	protected $fillable = ['id', 'slug', 'title', 'description', 'date', 'user_id'];

    public function media(){
        return $this->belongsToMany('\App\Media','media_notices');
    }

    public function user()
    {
        return $this->hasOne('App\User');
    }

	public static function saveData($request){

        $slug = str_replace(" ","-",strtolower($request->title));

		$noticeData = new Notice;

        $noticeData->slug        = $slug;
        $noticeData->title       = $request->title;
        $noticeData->description = $request->description;
        $noticeData->date        = $request->date;
        $noticeData->user_id     = Auth::User()->id;
        $noticeData->save();


        $nameFolder = 'notices/'.$slug.'-'.$noticeData->id.'/';
 
        $imagenes = static::getImages($request, $noticeData, $nameFolder);

        $videos = static::getVideos($request, $noticeData);


        return true;
    }

    public static function updateData($request, $id) {

        $notice = Notice::findOrFail($id);
        $media = $notice->media()->where('type','video')->get();

        $notice->title       = $request->title;
        $notice->description = $request->description;
        $notice->date        = $request->date;
        $notice->save();

        foreach ($media as $key => $value) {
            $mediaNotice = MediaNotice::where('media_id',$value->id)->get()->first();

            $mediaNotice->delete();
            $value->delete();
        }

        $nameFolder = 'notices/'.$notice->slug.'-'.$notice->id.'/';

        $imagenes = static::getImages($request, $notice, $nameFolder);

        $videos = static::getVideos($request, $notice);

        return true;
    }

    protected static function getVideos($request, $notice) {

        if(isset($request->videos[0])) {
            foreach ($request->videos as $videoKey => $videoValue) {

                $saveVideo   = Media::saveVideo($videoKey, $videoValue);
                $mediaNotice = MediaNotice::saveData($saveVideo->id, $notice->id);
            }
        }

        return;
    }

    protected static function getImages($request, $notice, $nameFolder) {

        if(isset($request->img)) {
            foreach ($request->img as $imgKey => $imgValue) {
                $saveImage   = Media::saveImg($imgKey, $imgValue, $nameFolder);
                $mediaNotice = MediaNotice::saveData($saveImage->id, $notice->id);
            }
        }

        return;
    }
}

app/Http/Controllers/NoticesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\NoticeRequest;
use App\Notice;
use App\Media;
use App\MediaNotice;
use Carbon\Carbon;

use Session;
use Redirect;
use DB;
use Gate;
use Auth;
use File;
use Validator;
use Storage;

class NoticesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('show.notice')) {
            abort(403);
        }

        $notices = Notice::get()->sortByDesc('created_at');

        return view('admin.notices.list',compact('notices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('create.notice')) {
            abort(403);
        }

        return view('admin.notices.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NoticeRequest $request)
    {
        if (Gate::denies('create.notice')) {
            abort(403);
        }

        $save = DB::transaction(function () use ($request) {
            $fileData = Notice::saveData($request);
            return $fileData;
        });


        if($save) {
            Session::flash('message','Guardada correctamente');
            return Redirect::to('/noticias/crear');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $searchItem = Notice::where('id',$id)->with('media')->get();

        $item = $searchItem->mapWithKeys(function ($item) {

            $media = $item->media->groupBy('type')->toArray();

            setlocale(LC_TIME, 'Spanish');
            $date = Carbon::parse($item->date)->formatLocalized('%A %d %B %Y');
       
            return [
                    'id'          => $item->id,
                    'date'        => $date,
                    'title'       => $item->title,
                    'description' => $item->description,
                    'items'       => $media
                ];

            
        })->toArray();

        return view('partials.notices.show',compact('item'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('edit.notice')) {
            abort(403);
        }

        $notice = Notice::findOrFail($id);

        $type = $notice->media->groupBy('type')->map(function ($item, $key) {
                return $item->sortByDesc('created_at');
            });

        return view('admin.notices.edit',compact('notice','type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NoticeRequest $request, $id)
    {
        if (Gate::denies('edit.notice')) {
            abort(403);
        }

        $save = DB::transaction(function () use ($request, $id) {
            $fileData = Notice::updateData($request, $id);
            return $fileData;
        });

        if($save) {
            Session::flash('message','Cambios guardados correctamente');
            return Redirect::to('/noticias/'.$id.'/editar');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('destroy.notice')) {
            abort(403);
        }

        $searchItem = Notice::find($id);
        $mediaNotice = MediaNotice::where('notice_id',$id)->get();

        $path = 'storage/notices/'.$searchItem->slug.'-'.$id;

        $deleted = File::deleteDirectory($path);

        $searchItem->media()->delete();

        $searchItem->delete();
        
        foreach ($mediaNotice as $key => $value) {
            $value->delete();
        }

        return;
    }

    public function destroyItem($id)
    {
        if (Gate::denies('destroy.notice')) {
            abort(403);
        }

        $item = Media::with('notice')->where('id',$id)->get()->first();
        $mediaNotice = MediaNotice::where('media_id',$id)->get()->first();

        $path = $item->url.$item->name;
        $pathThumb = $item->url.'thumb-'.$item->name;


        $deleted = File::delete($path, $pathThumb);

        $item->delete();
        $mediaNotice->delete();
      
        Session::flash('message','Se ha eliminado la imagen correctamente.');
        return redirect()->back();

    }

    public function validationImg($imgs) {
        $mime = ['jpeg','jpg','png'];

        $validator = Validator::make($imgs, []);

        foreach ($imgs as $key => $value) {
            $name    = $value->getClientOriginalName();
            $explode = explode('.',strtolower($name));

            if(!in_array($explode[1], $mime)) {
                $validator->errors()->add('img', 'El archivo "'.$name.'" no es del formato permitido.');
            }
        }

        return $validator;
    }

    public function validationVideo($videos) {
        $validator = Validator::make($videos, []);

        foreach ($videos as $key => $value) {
            $regex  = "/^(https?\:\/\/)?(www\.)?(youtube\.com)\/.+$/"; 
            $number = $key + 1;

            $idVideo = explode('watch?v=',$value);

            if(!preg_match($regex, $value, $output) || !isset($idVideo[1])) {

                $validator->errors()->add('img', 'El video "'.$number.'" no es del formato correcto.');
            }
        } 

        return $validator;
    }
}

resources/views/admin/notices/create.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Crear noticia')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'notice-create')
@section('class', 'notice-create')

@section('content')

    <div class="container">
        <div class="row row--margin">
            <div class="section-header">
                <h1 class="section-title text-center">Crear noticia</h1>
            </div>

            <div class="col-md-8 form_parent">

                <div id="alerts">
                    @include('alerts.success')
                    @include('alerts.error')
                    @include('alerts.warning')   
                </div>
    
               {!! Form::open(['route' => 'noticias.store',  'method' => 'POST', 'class' => 'form-horizontal form', 'files' => 'true', 'id' => 'save-notice']) !!}

                    @include('admin.notices.form')

                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

resources/views/admin/notices/edit.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Editar noticia')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'notice-edit')
@section('class', 'notice-edit')

@section('content')

    <div class="container">
        <div class="row row--margin">
     {{--        <div class="section-header">
                <h1 class="section-title text-center">Editar noticia</h1>
            </div> --}}
            <div class="col-md-8 form_parent">

                <div id="alerts">
                    @include('alerts.success')
                    @include('alerts.error')
                    @include('alerts.warning')   
                </div>
                
                {{ Form::model($notice, array('route' => array('noticias.update',$notice->id), 'method' => 'PUT', 'class' => 'form-horizontal form', 'files' => 'true', 'id' => 'save-notice')) }}

                    @include('admin.notices.form')


                {!! Form::close() !!}

            </div>
        </div>
    </div>

@endsection

resources/views/admin/notices/form.blade.php
  <div class="form-group">
    {!! Form::label('title', 'Título:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      {!! Form::text('title',isset($notice) ? $notice->title : null, ['class' => 'form-control', 'maxlength' => 85]) !!}
    </div>
  </div>

  <div class="form-group">
    {!! Form::label('description', 'Descripción:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      {!! Form::textarea('description', isset($notice) ? $notice->description : null, ['class' => 'form-control']) !!}
    </div>
  </div>

  <div class="form-group">
    {!! Form::label('date', 'Fecha:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      {!! Form::date('date', isset($notice) ? $notice->date : null, ['class' => 'form-control']) !!}
    </div>
  </div>

  <h4 class="">Imagenes <small>(Opcional)</small></h4>
  <div class="form-group">
    <div class="col-sm-10 align-self-end float-right">
      @if(isset($type['img']))
        @foreach($type['img'] as $key => $img)
        <div class="img-container  col-lg-3 col-sm-3 col-xs-4">
          <a href="{{ route('noticias.delete.item',$img->id) }}" class="delete-img fa fa-plus fa-rotate-42"></a>
            <img src="{{ url($img->url.'thumb-'.$img->name) }}" alt="">
        </div>
          
        @endforeach
      @endif
    </div>
  </div>

  <div class="form-group">
    <input type="text" name="data-images" class="hidden" value="{{ isset($type['img']) ? 'true' : 'false' }}">
    {!! Form::label('img', isset($notice) ? 'Agregar:' : 'Seleccionar:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      <input type="file" id="img[]" name="img[]" multiple="true">
      <small class="form-text text-muted">Seleccione únicamente imagenes con formato .jpg, .jpeg, y .png</small>
    </div>
  </div>

  <h4 class="">Videos <small>(Opcional)</small></h4>

  <div id="videos-container">

  @if(isset($type['video']))
    @foreach($type['video'] as $key => $video)
      <div class="form-group">
       {!! Form::label('videos',($key + 1).'.',['class' => 'col-sm-2 text-right']) !!}
        <div class="col-sm-10 align-self-end float-right item-video">
          {!! Form::textarea('videos[]', 'https://www.youtube.com/watch?v='.$video->url, ['class' => 'form-control col-sm-10','rows' => 2]) !!}
          <a class="delete-item-video"=><i class="fa fa-plus fa-rotate-42"></i></a>
        </div>
      </div> 
    @endforeach
  @else
    <div class="form-group">
       {!! Form::label('videos', '1.',['class' => 'col-sm-2 text-right']) !!}
        <div class="col-sm-10 align-self-end float-right item-video">
          {!! Form::textarea('videos[]', null, ['class' => 'form-control col-sm-10','rows' => 2]) !!}
          <a class="delete-item-video"=><i class="fa fa-plus fa-rotate-42"></i></a>
        </div>
      </div> 
  @endif
  </div>

  <div class="col-sm-10 align-self-end float-right">
    <a id="add-video-btn" class="add-video"><i class="fa fa-plus"></i>Ingresar otro video</a>
    <small class="small-alert none"><b> Ha llegado al limite de videos</b></small>
  </div>

  <div class="text-center med-margin-top">
    <button type="submit" class="btn btn-primary btn-lg js-save-notice" data-csrf="{{ csrf_token() }}" data-method="{{ isset($notice) ? 'PUT' : 'POST' }}" data-notice="{{ isset($notice) ? '/'.$notice->id : '' }}">Guardar <span class="fa fa-spinner fa-spin hidden"></span></button>
  </div>

resources/views/admin/notices/list.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Noticias')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'notices-list')
@section('class', 'notices-list')

@section('content')

  <div class="container">
    <div class="row row--margin">
      <div class="section-header">
          <h1 class="section-title text-center wow fadeInDown ">Noticias</h1>
      </div>

      <div class="text-right">
         <a href="{{ route('noticias.create') }}" class="btn btn-primary" role="button" aria-pressed="true">Crear noticia</a>
      </div>

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Titulo</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @if($notices == '[]')
            <tr>
                <th colspan="2" class="text-center">Sin resultados</th>
            </tr>
          @else         
            @foreach($notices as $notice)
              <tr>
                <th>{{ $notice->title }}</th>
                <td class="text-center">
                  <a href="{{ url('noticias',$notice->id) }}" class="btn btn-sm btn-success " role="button" aria-pressed="true" >Ver</a>
                  <a href="{{ route('noticias.edit',$notice->id) }}" class="btn btn-sm btn-info" role="button" aria-pressed="true">Editar</a>
                  <a class="btn btn-sm btn-danger js-delete-notice" role="button" aria-pressed="true" data-item="{{ $notice->id }}" data-csrf="{{ csrf_token() }}">Eliminar</a>
                </td>
              </tr>
            @endforeach
          @endif
        </tbody>
      </table>
    </div>
  </div>

@endsection