routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Home
Route::get('/', 'ContentController@home');

// ADMIN
Route::get('/admin', 'Auth\LoginController@getAdmin');

// Route::get('/cambiar-contraseña', function () {
//     return view('emails.contact');
// });

//Login
Route::post('/iniciar-sesion', 'Auth\LoginController@postLogin');

// Logout
Route::get('/cerrar-sesion','Auth\LoginController@getLogout');

//Change pass
Route::get('/cambiar-contrasena', 'Auth\ResetPasswordController@index');
Route::post('/cambiar-contrasena/{id}', 'Auth\ResetPasswordController@update');

//Galery
Route::resource('galeria', 'GaleryController');
Route::get('/admin/galeria', 'GaleryController@index');
Route::delete('/admin/galeria/delete/{id}', ['as' => 'galeria.delete', 'uses' => 'GaleryController@destroy']);
Route::get('/admin/galeria/delete-item/{id}', ['as' => 'galeria.delete.item', 'uses' => 'GaleryController@destroyItem']);


Route::resource('noticias', 'NoticesController');
Route::get('/admin/noticias', 'NoticesController@index');
Route::delete('/admin/noticias/delete/{id}', ['as' => 'noticias.delete', 'uses' => 'NoticesController@destroy']);
Route::get('/admin/noticias/delete-item/{id}', ['as' => 'noticias.delete.item', 'uses' => 'NoticesController@destroyItem']);


Route::post('/send-email', 'EmailController@send');

// PUBLIC
Route::get('/nosotros', function () {
    return view('partials.about.more');
});

Route::get('/noticias', 'ContentController@moreNotices');
Route::get('/galeria', 'ContentController@moreGalery');

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Media;
use App\MediaNotice;
use Auth;

class Notice extends Model
{
	protected $table = 'notices';
	protected $fillable = ['id', 'slug', 'title', 'description', 'date', 'user_id'];

    public function media(){
        return $this->belongsToMany('\App\Media','media_notices');
    }

    public function user()
    {
        return $this->hasOne('App\User');
    }

	public static function saveData($request){

        $slug = str_replace(" ","-",strtolower($request->title));

		$noticeData = new Notice;

        $noticeData->slug        = $slug;
        $noticeData->title       = $request->title;
        $noticeData->description = $request->description;
        $noticeData->date        = $request->date;
        $noticeData->user_id     = Auth::User()->id;
        $noticeData->save();


        $nameFolder = 'notices/'.$slug.'-'.$noticeData->id.'/';
 
        $imagenes = static::getImages($request, $noticeData, $nameFolder);

        $videos = static::getVideos($request, $noticeData);


        return true;
    }

    public static function updateData($request, $id) {

        $notice = Notice::findOrFail($id);
        $media = $notice->media()->where('type','video')->get();

        $notice->title       = $request->title;
        $notice->description = $request->description;
        $notice->date        = $request->date;
        $notice->save();

        foreach ($media as $key => $value) {
            $mediaNotice = MediaNotice::where('media_id',$value->id)->get()->first();

            $mediaNotice->delete();
            $value->delete();
        }

        $nameFolder = 'notices/'.$notice->slug.'-'.$notice->id.'/';

        $imagenes = static::getImages($request, $notice, $nameFolder);

        $videos = static::getVideos($request, $notice);

        return true;
    }

    protected static function getVideos($request, $notice) {

        if(isset($request->videos[0])) {
            foreach ($request->videos as $videoKey => $videoValue) {

                $saveVideo   = Media::saveVideo($videoKey, $videoValue);
                $mediaNotice = MediaNotice::saveData($saveVideo->id, $notice->id);
            }
        }

        return;
    }

    protected static function getImages($request, $notice, $nameFolder) {

        if(isset($request->img)) {
            foreach ($request->img as $imgKey => $imgValue) {
                $saveImage   = Media::saveImg($imgKey, $imgValue, $nameFolder);
                $mediaNotice = MediaNotice::saveData($saveImage->id, $notice->id);
            }
        }

        return;
    }
}

app/Http/Controllers/NoticesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\NoticeRequest;
use App\Notice;
use App\Media;
use App\MediaNotice;
use Carbon\Carbon;

use Session;
use Redirect;
use DB;
use Gate;
use Auth;
use File;
use Validator;
use Storage;

class NoticesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('show.notice')) {
            abort(403);
        }

        $notices = Notice::get()->sortByDesc('created_at');

        return view('admin.notices.list',compact('notices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('create.notice')) {
            abort(403);
        }

        return view('admin.notices.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NoticeRequest $request)
    {
        if (Gate::denies('create.notice')) {
            abort(403);
        }

        $save = DB::transaction(function () use ($request) {
            $fileData = Notice::saveData($request);
            return $fileData;
        });


        if($save) {
            Session::flash('message','Guardada correctamente');
            return Redirect::to('/noticias/crear');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $searchItem = Notice::where('id',$id)->with('media')->get();

        $item = $searchItem->mapWithKeys(function ($item) {

            $media = $item->media->groupBy('type')->toArray();

            setlocale(LC_TIME, 'Spanish');
            $date = Carbon::parse($item->date)->formatLocalized('%A %d %B %Y');
       
            return [
                    'id'          => $item->id,
                    'date'        => $date,
                    'title'       => $item->title,
                    'description' => $item->description,
                    'items'       => $media
                ];

            
        })->toArray();

        return view('partials.notices.show',compact('item'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('edit.notice')) {
            abort(403);
        }

        $notice = Notice::findOrFail($id);

        $type = $notice->media->groupBy('type')->map(function ($item, $key) {
                return $item->sortByDesc('created_at');
            });

        return view('admin.notices.edit',compact('notice','type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(NoticeRequest $request, $id)
    {
        if (Gate::denies('edit.notice')) {
            abort(403);
        }

        $save = DB::transaction(function () use ($request, $id) {
            $fileData = Notice::updateData($request, $id);
            return $fileData;
        });

        if($save) {
            Session::flash('message','Cambios guardados correctamente');
            return Redirect::to('/noticias/'.$id.'/editar');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('destroy.notice')) {
            abort(403);
        }

        $searchItem = Notice::find($id);
        $mediaNotice = MediaNotice::where('notice_id',$id)->get();

        $path = 'storage/notices/'.$searchItem->slug.'-'.$id;

        $deleted = File::deleteDirectory($path);

        $searchItem->media()->delete();

        $searchItem->delete();
        
        foreach ($mediaNotice as $key => $value) {
            $value->delete();
        }

        return;
    }

    public function destroyItem($id)
    {
        if (Gate::denies('destroy.notice')) {
            abort(403);
        }

        $item = Media::with('notice')->where('id',$id)->get()->first();
        $mediaNotice = MediaNotice::where('media_id',$id)->get()->first();

        $path = $item->url.$item->name;
        $pathThumb = $item->url.'thumb-'.$item->name;


        $deleted = File::delete($path, $pathThumb);

        $item->delete();
        $mediaNotice->delete();
      
        Session::flash('message','Se ha eliminado la imagen correctamente.');
        return redirect()->back();

    }

    public function validationImg($imgs) {
        $mime = ['jpeg','jpg','png'];

        $validator = Validator::make($imgs, []);

        foreach ($imgs as $key => $value) {
            $name    = $value->getClientOriginalName();
            $explode = explode('.',strtolower($name));

            if(!in_array($explode[1], $mime)) {
                $validator->errors()->add('img', 'El archivo "'.$name.'" no es del formato permitido.');
            }
        }

        return $validator;
    }

    public function validationVideo($videos) {
        $validator = Validator::make($videos, []);

        foreach ($videos as $key => $value) {
            $regex  = "/^(https?\:\/\/)?(www\.)?(youtube\.com)\/.+$/"; 
            $number = $key + 1;

            $idVideo = explode('watch?v=',$value);

            if(!preg_match($regex, $value, $output) || !isset($idVideo[1])) {

                $validator->errors()->add('img', 'El video "'.$number.'" no es del formato correcto.');
            }
        } 

        return $validator;
    }
}

resources/views/partials/notices/more.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Noticias')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'blog')
@section('class', 'home')

@section('content')

  <section class="custom_section">
    <div class="container">
      <div class="section-header">
          <h1 class="section-title text-center wow fadeInDown">Noticias</h2>
      </div>

      <div class="row">
        
        @foreach($notices as $notice)
          <div class="col-lg-3 col-md-3 col-xs-3 padding-30 padding-b-30">
              <div class="blog-post blog-large wow fadeInLeft" data-wow-duration="300ms" data-wow-delay="0ms">
                  <article>
                      <div class="entry-header">
                          <div class="entry-thumbnail entry-thumbnail--main">
                              <img class="img-responsive" src="{{ url($notice->media[0]->url.'thumb-'.$notice->media[0]->name) }}" alt="">

                              <span class="post-format post-format-{{ $notice->media[0]->type = 'img' ? 'galery' : 'video' }} "><i class="fa {{ $notice->media[0]->type = 'img' ? 'fa-picture-o' : 'fa-film'  }}"></i></span>
                          </div>
                      </div>

                      <div class="entry-content">
                          <div class="entry-date">{{ \Carbon\Carbon::parse($notice->date)->diffForHumans() }}</div>
                          <h2 class="entry-title"><a href="{{ route('noticias.show',$notice->id) }}">{{ $notice->title }}</a></h2>
                          <P class="ellipsis"> <?php echo nl2br($notice->description); ?> </P>
                          <a class="btn btn-primary" href="{{ route('noticias.show',$notice->id) }}">Leer Más</a>
                      </div>

                  </article>
              </div>
          </div>
        @endforeach
      </div>

    </div>
    
  </section>

@endsection

resources/views/partials/notices/section.blade.php
    <section id="blog">
        <div class="container">
            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown">Noticias</h2>
                <p class="text-center wow fadeInDown">Somos una asociación civil proactiva siempre buscando la oportunidad de involucrar a la sociedad de Durango, en el ayudar a otros. Creemos que todos podemos aportar algo a favor de quien se encuentra en necesidad.</p>
            </div>

            <div class="row">

            @foreach($notices as $notice)
                <div class="col-lg-3 col-md-3 col-xs-3 padding-30">
                    <div class="blog-post blog-large wow fadeInLeft" data-wow-duration="300ms" data-wow-delay="0ms">
                        <article>
                            <div class="entry-header">
                                <div class="entry-thumbnail entry-thumbnail--main">
                                    <img class="img-responsive" src="{{ url($notice->media[0]->url.'thumb-'.$notice->media[0]->name) }}" alt="">

                                    <span class="post-format post-format-{{ $notice->media[0]->type = 'img' ? 'galery' : 'video' }} "><i class="fa {{ $notice->media[0]->type = 'img' ? 'fa-picture-o' : 'fa-film'  }}"></i></span>
                                </div>
                            </div>

                            <div class="entry-content">
                                <div class="entry-date">{{ \Carbon\Carbon::parse($notice->date)->diffForHumans() }}</div>
                                <h2 class="entry-title"><a href="{{ route('noticias.show',$notice->id) }}">{{ $notice->title }}</a></h2>
                                <P class="ellipsis"> <?php echo nl2br($notice->description); ?> </P>
                                <a class="btn btn-primary" href="{{ route('noticias.show',$notice->id) }}">Leer Más</a>
                            </div>

                        </article>
                    </div>
                </div><!--/.col-sm-6-->

            @endforeach

                <div class="text-right show-more">
                    <a class="btn btn-primary" href="{{ url('/noticias') }}">Ver Más</a>
                </div>   
            </div>
        </div>
    </section>

resources/views/partials/notices/show.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Noticias')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'notices-show')
@section('class', 'notices-show')

@section('content')
<div class="container">
    <div class="row row--margin ">
      <div class="section-header">
        <h1 class="section-title text-center">{{ $item['title'] }}</h1>
        
        <div class="col-md-10 container-media text-left">
        <p><i>por: </i> <span>C.A.S.A.</span> <i>publicada el</i> <span>{{ $item['date'] }}</span></p>
        </div>
        
      </div> 

	<div class="col-md-10 container-media text-left">
		<p> <?php echo nl2br($item['description']); ?> </p>

	</div>
      @if(isset($item['items']['img']))
        @include('partials.galery.img')
      @endif

      @if(isset($item['items']['video']))
        @include('partials.galery.video')
      @endif
    </div>
  </div>

  @include('partials.galery.modal')
{{--   
  <div class="container">
    <div class="row row--margin">
      <div class="section-header">
        <h1 class="section-title text-center">{{ $item['title'] }}</h1>
      </div> 

          @include('partials.notices.item')

      @if(isset($item['items']['img']))
        @include('partials.galery.img')
      @endif

      @if(isset($item['items']['video']))
        @include('partials.galery.video')
      @endif

    </div>
  </div>



    @include('partials.galery.modal') --}}
    
@endsection