routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Home
Route::get('/', 'ContentController@home');

// ADMIN
Route::get('/admin', 'Auth\LoginController@getAdmin');

// Route::get('/cambiar-contraseña', function () {
//     return view('emails.contact');
// });

//Login
Route::post('/iniciar-sesion', 'Auth\LoginController@postLogin');

// Logout
Route::get('/cerrar-sesion','Auth\LoginController@getLogout');

//Change pass
Route::get('/cambiar-contrasena', 'Auth\ResetPasswordController@index');
Route::post('/cambiar-contrasena/{id}', 'Auth\ResetPasswordController@update');

//Galery
Route::resource('galeria', 'GaleryController');
Route::get('/admin/galeria', 'GaleryController@index');
Route::delete('/admin/galeria/delete/{id}', ['as' => 'galeria.delete', 'uses' => 'GaleryController@destroy']);
Route::get('/admin/galeria/delete-item/{id}', ['as' => 'galeria.delete.item', 'uses' => 'GaleryController@destroyItem']);


Route::resource('noticias', 'NoticesController');
Route::get('/admin/noticias', 'NoticesController@index');
Route::delete('/admin/noticias/delete/{id}', ['as' => 'noticias.delete', 'uses' => 'NoticesController@destroy']);
Route::get('/admin/noticias/delete-item/{id}', ['as' => 'noticias.delete.item', 'uses' => 'NoticesController@destroyItem']);


Route::post('/send-email', 'EmailController@send');

// PUBLIC
Route::get('/nosotros', function () {
    return view('partials.about.more');
});

Route::get('/noticias', 'ContentController@moreNotices');
Route::get('/galeria', 'ContentController@moreGalery');

app/Galery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Media;
use App\MediaGalery;

class Galery extends Model
{
	protected $table = 'galeries';
	protected $fillable = ['id', 'title','description', 'slug','date'];


    public function media(){
        return $this->belongsToMany('\App\Media','media_galeries');
    }

	public static function saveData($request){
        $slug = str_replace(" ","-",strtolower($request->title));

        $galeryData = new Galery;

        $galeryData->slug        = $slug;
        $galeryData->title       = $request->title;
        $galeryData->description = $request->description;
        $galeryData->date        = $request->date;
        $galeryData->save();

        $nameFolder = 'galery/'.$slug.'-'.$galeryData->id.'/';
        
        $imagenes = static::getImages($request, $galeryData, $nameFolder);

        $videos = static::getVideos($request, $galeryData);

        return true;
    }

    public static function updateData($request, $id){

        $galery = Galery::findOrFail($id);
        $media  = $galery->media()->where('type','video')->get();

        $galery->title       = $request->title;
        $galery->description = $request->description;
        $galery->date        = $request->date;
        $galery->save();

        foreach ($media as $key => $value) {
            $mediaGalery = MediaGalery::where('media_id',$value->id)->get()->first();

            $mediaGalery->delete();
            $value->delete();
        }

        $nameFolder = 'galery/'.$galery->slug.'-'.$galery->id.'/';

        $imagenes = static::getImages($request, $galery, $nameFolder);

        $videos = static::getVideos($request, $galery);

        return true;
    }

    protected static function getVideos($request, $galery) {

        if(isset($request->videos[0])) {
            foreach ($request->videos as $videoKey => $videoValue) {

                $saveVideo   = Media::saveVideo($videoKey, $videoValue);
                $mediaNotice = MediaGalery::saveData($saveVideo->id, $galery->id);
            }
        }

        return;
    }

    protected static function getImages($request, $galery, $nameFolder) {

        if(isset($request->img)) {
            foreach ($request->img as $imgKey => $imgValue) {
                $saveImage   = Media::saveImg($imgKey, $imgValue, $nameFolder);
                $mediaNotice = MediaGalery::saveData($saveImage->id, $galery->id);
            }
        }

        return;
    }
}

app/Http/Controllers/GaleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\GaleryRequest;
use App\Galery;
use App\Media;
use App\MediaGalery;
use Carbon\Carbon;

use Session;
use Redirect;
use DB;
use Gate;
use File;
use Validator;
use Storage;


class GaleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('show.galery')) {
            abort(403);
        }

        $folders = Galery::get()->sortByDesc('created_at');

        return view('admin.galery.list', compact('folders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        if (Gate::denies('create.galery')) {
            abort(403);
        }

        return view('admin.galery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GaleryRequest $request)
    {
        if (Gate::denies('create.galery')) {
            abort(403);
        }

        $save = DB::transaction(function () use ($request) {
            $fileData = Galery::saveData($request);
            return $fileData;
        });

        if($save) {
            return 'success';
            Session::flash('message','Guardada correctamente');
            return Redirect::to('/galeria/crear');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $searchItem = Galery::where('id',$id)->with('media')->get();

        $item = $searchItem->mapWithKeys(function ($item) {

            setlocale(LC_TIME, 'Spanish');
            $date = Carbon::parse($item->date)->formatLocalized('%A %d %B %Y');

            $media = $item->media->groupBy('type')->toArray();

            return [   
                    'id'          => $item->id,
                    'title'       => $item->title,
                    'date'        => $date,
                    'description' => $item->description,
                    'items'       => $media
                ];

            
        })->toArray();

        return view('partials.galery.show',compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('edit.galery')) {
            abort(403);
        }

        $galery = Galery::findOrFail($id);

        $type = $galery->media->groupBy('type')->map(function ($item, $key) {
                return $item->sortByDesc('created_at');
            });

        return view('admin.galery.edit',compact('galery','type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(GaleryRequest $request, $id)
    {
        if (Gate::denies('edit.galery')) {
            abort(403);
        }

        $save = DB::transaction(function () use ($request, $id) {
            $fileData = Galery::updateData($request, $id);
            return $fileData;
        });

        if($save) {
            Session::flash('message','Cambios guardados correctamente');
            return Redirect::to('/galeria/'.$id.'/editar');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('delete.galery')) {
            abort(403);
        }

        $searchItem = Galery::find($id);
        $mediaGalery = MediaGalery::where('galery_id',$id)->get();

        $path = 'galery/'.$searchItem->slug.'-'.$id;

        Storage::deleteDirectory($path);

        $searchItem->media()->delete();

        $searchItem->delete();

        foreach ($mediaGalery as $key => $value) {
   
            $value->delete();
        }

        return;
    }

    public function destroyItem($id)
    {
        if (Gate::denies('destroy.galery')) {
            abort(403);
        }

        $item = Media::with('galery')->where('id',$id)->get()->first();
        $mediaGalery = MediaGalery::where('media_id',$id)->get()->first();

        $path = $item->url.$item->name;
        $pathThumb = $item->url.'thumb-'.$item->name;


        $deleted = File::delete($path, $pathThumb);

        $item->delete();
        $mediaGalery->delete();
      
        Session::flash('message','Se ha eliminado la imagen correctamente.');
        return redirect()->back();

    }

    public function validationImg($imgs) {
        $mime = ['jpeg','jpg','png'];

        $validator = Validator::make($imgs, []);

        foreach ($imgs as $key => $value) {
            $name    = $value->getClientOriginalName();
            $explode = explode('.',strtolower($name));

            if(!in_array($explode[1], $mime)) {
                $validator->errors()->add('img', 'El archivo "'.$name.'" no es del formato permitido.');
            }
        }

        return $validator;
    }

    public function validationVideo($videos) {
        $validator = Validator::make($videos, []);

        foreach ($videos as $key => $value) {
            $regex  = "/^(https?\:\/\/)?(www\.)?(youtube\.com)\/.+$/"; 
            $number = $key + 1;

            $idVideo = explode('watch?v=',$value);

            if(!preg_match($regex, $value, $output) || !isset($idVideo[1])) {

                $validator->errors()->add('img', 'El video "'.$number.'" no es del formato correcto.');
            }
        } 

        return $validator;
    }
}

resources/views/admin/galery/create.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Subir foto')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'galery-create')
@section('class', 'galery-create')

@section('content')

    <div class="container">
        <div class="row row--margin">
            <div class="section-header">
                <h1 class="section-title text-center">Crear album</h1>
            </div>

            <div class="col-md-8 form_parent">

                <div id="alerts">
                    @include('alerts.success')
                    @include('alerts.error')
                    @include('alerts.warning')   
                </div>

                {!! Form::open(['route' => 'galeria.store',  'method' => 'POST', 'class' => 'form-horizontal form ', 'files' => 'true', 'id' => 'save-galery']) !!}

                    @include('admin.galery.form')

                {!! Form::close() !!}

            </div>
        </div>
    </div>
    

@endsection

resources/views/admin/galery/edit.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Editar foto')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'galery-edit')
@section('class', 'galery-edit')

@section('content')

    <div class="container">
        <div class="row row--margin">
           <div class="section-header">
                <h1 class="section-title text-center">Editar</h1>
            </div>

            <div class="col-md-8 form_parent">

                <div id="alerts">
                    @include('alerts.success')
                    @include('alerts.error')
                    @include('alerts.warning')   
                </div>

                {{ Form::model($galery, array('route' => array('galeria.update',$galery->id), 'method' => 'PUT', 'class' => 'form-horizontal form', 'files' => 'true', 'id' => 'save-galery')) }}

                    @include('admin.galery.form')

                {!! Form::close() !!}

            </div>
        </div>
    </div>

@endsection

resources/views/admin/galery/form.blade.php
  <div class="form-group">
    {!! Form::label('title', 'Título:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      {!! Form::text('title', isset($galery) ? $galery->title : null, ['class' => 'form-control', 'maxlength' => 85]) !!}
    </div>
  </div>

  <div class="form-group">
    {!! Form::label('description', 'Descripción corta:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      {!! Form::textarea('description', isset($galery) ? $galery->description : null, ['class' => 'form-control', 'maxlength' => 300,'rows' => 4]) !!}
    </div>
  </div>

  <div class="form-group">
    {!! Form::label('date', 'Fecha:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      {!! Form::date('date', isset($galery) ? $galery->date : null, ['class' => 'form-control']) !!}
    </div>
  </div>

  <h4 class="">Imagenes <small>(Opcional)</small></h4>
  <div class="form-group">
    <div class="col-sm-10 align-self-end float-right">
      @if(isset($type['img']))
        @foreach($type['img'] as $key => $img)
        <div class="img-container col-lg-3 col-sm-3 col-xs-4">
          <a href="{{ route('galeria.delete.item',$img->id) }}" class="delete-img fa fa-plus fa-rotate-42"></a>
            <img src="{{ url($img->url.'thumb-'.$img->name) }}" alt="">
        </div>
        @endforeach
      @endif
    </div>
  </div>

  <div class="form-group">
    {!! Form::label('img', isset($galery) ? 'Agregar:' : 'Seleccionar:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
      <input type="file" id="img[]" name="img[]" multiple="true">
      <small class="form-text text-muted">Seleccione únicamente imagenes con formato .jpg, .jpeg, y .png</small>
    </div>
  </div>

  <h4 class="">Videos <small>(Opcional)</small></h4>

  <div id="videos-container">

  @if(isset($type['video']))
    @foreach($type['video'] as $key => $video)
      <div class="form-group">
       {!! Form::label('videos',($key + 1).'.',['class' => 'col-sm-2 text-right']) !!}
        <div class="col-sm-10 align-self-end float-right item-video">
          {!! Form::textarea('videos[]', 'https://www.youtube.com/watch?v='.$video->url, ['class' => 'form-control col-sm-10','rows' => 2]) !!}
          <a class="delete-item-video"=><i class="fa fa-plus fa-rotate-42"></i></a>
        </div>
      </div> 
    @endforeach
  @else
    <div class="form-group">
       {!! Form::label('videos', '1.',['class' => 'col-sm-2 text-right']) !!}
        <div class="col-sm-10 align-self-end float-right item-video">
          {!! Form::textarea('videos[]', null, ['class' => 'form-control col-sm-10','rows' => 2]) !!}
          <a class="delete-item-video"><i class="fa fa-plus fa-rotate-42"></i></a>
        </div>
      </div> 
  @endif
  </div>

  <div class="col-sm-10 align-self-end float-right">
    <a id="add-video-btn" class="add-video"><i class="fa fa-plus"></i>Ingresar otro video</a>
    <small class="small-alert none"><b> Ha llegado al limite de videos</b></small>
  </div>

  <div class="text-center med-margin-top">
    <button type="submit" class="btn btn-primary btn-lg js-save-galery" data-csrf="{{ csrf_token() }}" data-method="{{ isset($galery) ? 'PUT' : 'POST' }}" data-galery="{{ isset($galery) ? '/'.$galery->id : '' }}">Guardar <span class="fa fa-spinner fa-spin hidden"></span></button>
  </div>

resources/views/admin/galery/list.blade.php
@extends('layout.master')

{{-- Metadata --}}
@section('meta.title', 'C.A.S.A.')
@section('meta.tab_title', 'Galeria')
@section('meta.description', '')
@section('meta.canonical')
@section('id', 'galery-list')
@section('class', 'galery-list')

@section('content')

  <div class="container">
    <div class="row row--margin">
      <div class="section-header">
          <h1 class="section-title text-center">Galeria</h1>
      </div>

      <div class="text-right">
         <a href="{{ route('galeria.create') }}" class="btn btn-primary" role="button" aria-pressed="true">Crear album</a>
      </div>
     
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Titulo</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @if($folders == '[]')
            <tr>
                <th colspan="3" class="text-center">Sin resultados</th>
            </tr>
          @else     
            @foreach($folders as $folder)
              <tr>
                <th>{{ $folder->title }}</th>
                <td class="text-center">
                  <a href="{{ route('galeria.show',$folder->id) }}" class="btn btn-sm btn-success " role="button" aria-pressed="true" >Ver</a>
                  <a href="{{ route('galeria.edit',$folder->id) }}" class="btn btn-sm btn-info" role="button" aria-pressed="true">Editar</a>
                  <a class="btn btn-sm btn-danger js-delete-galery" role="button" aria-pressed="true" data-item="{{ $folder->id }}" data-csrf="{{ csrf_token() }}">Eliminar</a>
                </td>
              </tr>
            @endforeach
          @endif     
        </tbody>
      </table>
    </div>
  </div>

@endsection